"
I contain simple visual morphic installer interface
"
Class {
	#name : #ManifestGToolkitLibraryInstallerMorphic,
	#superclass : #PackageManifest,
	#category : #'GToolkit-LibraryInstaller-Morphic'
}

{ #category : #'code-critics' }
ManifestGToolkitLibraryInstallerMorphic class >> ruleRBCascadedNextPutAllsRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#'GToolkit-LibraryInstaller')) #'2018-11-04T14:08:36.670661+01:00') )
]

{ #category : #'code-critics' }
ManifestGToolkitLibraryInstallerMorphic class >> ruleRBContainsRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#'GToolkit-LibraryInstaller')) #'2018-11-04T13:43:58.157684+01:00') )
]

{ #category : #'code-critics' }
ManifestGToolkitLibraryInstallerMorphic class >> ruleRBUtilityMethodsRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#'GToolkit-LibraryInstaller')) #'2018-11-04T13:44:01.274073+01:00') )
]
